#ifndef USER_CONFIG_H
#define USER_CONFIG_H

#include "pmsm_motor_parameters.h"

/* Control mode selection */
#define USER_CONTROL_MODE_THROTTLE 1
#define USER_CONTROL_MODE_POSITION_AS5600 2
#define USER_CONTROL_MODE_FOLLOW_AS5600_KNOB 3
#define USER_CONTROL_MODE_LOW_SPEED_SPIN_TEST 4
#define USER_CONTROL_MODE_UART_TARGET_AS5600 5
#define USER_CONTROL_MODE_PWM_TARGET_AS5600 6

/* App-level motor profile selection */
#define USER_MOTOR_PROFILE_2216_920KV 1
#define USER_MOTOR_PROFILE_2804_100KV 2
#define USER_MOTOR_PROFILE_2804_220KV 3

/* Startup / rev-up selection */
#define USER_STARTUP_PROFILE_MCW_DEFAULT 1
#define USER_STARTUP_PROFILE_2804_GENTLE_SENSORLESS 2
#define USER_STARTUP_PROFILE_2804_LOW_SPEED_TEST 3

/* FOC backend selection derived from the active control mode */
#define USER_FOC_BACKEND_SENSORLESS 1
#define USER_FOC_BACKEND_AS5600_SENSORED 2

/* Position loop output selection */
#define USER_POS_OUTPUT_MODE_CURRENT 1
#define USER_POS_OUTPUT_MODE_SPEED 2

/*
 * Active setup:
 * - Use an external PWM pulse stream on J3/PA15 as the target angle source.
 * - Drive the local MKS 2804 220KV through the AS5600-based sensored FOC
 *   skeleton, with the position loop currently using a user-owned
 *   position -> speed -> current cascade follower.
 * - Keep the original 2216 sensorless throttle mode and the other user modes
 *   available behind USER_CONTROL_MODE.
 */
#define USER_CONTROL_MODE USER_CONTROL_MODE_PWM_TARGET_AS5600
#define USER_MOTOR_PROFILE USER_MOTOR_PROFILE_2804_220KV
#define USER_STARTUP_PROFILE USER_STARTUP_PROFILE_2804_GENTLE_SENSORLESS
#define USER_POSITION_OUTPUT_MODE USER_POS_OUTPUT_MODE_SPEED
#define USER_POS_BOOT_ALIGN_TO_SHAFT 0U

#if (USER_CONTROL_MODE == USER_CONTROL_MODE_POSITION_AS5600) || \
    (USER_CONTROL_MODE == USER_CONTROL_MODE_UART_TARGET_AS5600) || \
    (USER_CONTROL_MODE == USER_CONTROL_MODE_PWM_TARGET_AS5600)
#define USER_FOC_BACKEND USER_FOC_BACKEND_AS5600_SENSORED
#else
#define USER_FOC_BACKEND USER_FOC_BACKEND_SENSORLESS
#endif

#if (USER_CONTROL_MODE == USER_CONTROL_MODE_UART_TARGET_AS5600) || \
    (USER_CONTROL_MODE == USER_CONTROL_MODE_PWM_TARGET_AS5600)
#define USER_PLATFORM_OWNS_USART2 1U
#else
#define USER_PLATFORM_OWNS_USART2 0U
#endif

#if (USER_POSITION_OUTPUT_MODE != USER_POS_OUTPUT_MODE_CURRENT) && \
    (USER_POSITION_OUTPUT_MODE != USER_POS_OUTPUT_MODE_SPEED)
#error "Unsupported USER_POSITION_OUTPUT_MODE."
#endif

/*
 * The low-level MCSDK / Workbench motor tune still comes from generated files
 * such as pmsm_motor_parameters.h, drive_parameters.h, and
 * mc_configuration_registers.c.
 *
 * Update this macro after you regenerate MC Workbench for another motor.
 */
#define USER_MCSDK_TUNE_PROFILE USER_MOTOR_PROFILE_2216_920KV

/*
 * Safety gate:
 * - 0: stop the build when the selected app profile and MCSDK motor tune do
 *      not match.
 * - 1: allow intentional mismatch for bring-up / wiring / early tests.
 */
#define USER_ALLOW_PROFILE_MISMATCH 1

#if (USER_MOTOR_PROFILE != USER_MCSDK_TUNE_PROFILE) && (USER_ALLOW_PROFILE_MISMATCH == 0)
#error "USER_MOTOR_PROFILE does not match USER_MCSDK_TUNE_PROFILE. Regenerate MC Workbench or explicitly allow the mismatch."
#endif

#if (USER_MOTOR_PROFILE == USER_MOTOR_PROFILE_2216_920KV) && \
    (USER_STARTUP_PROFILE != USER_STARTUP_PROFILE_MCW_DEFAULT)
#error "2216 profile currently supports only USER_STARTUP_PROFILE_MCW_DEFAULT."
#endif

/* Shared potentiometer mapping */
#define USER_POT_CENTER 32768U
#define USER_POT_DEADBAND 2000U
#define USER_POT_MIN 0U
#define USER_POT_MAX 65520U

/*
 * Position-mode potentiometer calibration:
 * Trim the mechanical dead zones near both ends of the slider so the effective
 * travel maps cleanly to one AS5600 turn.
 */
#define USER_POS_POT_EFFECTIVE_MIN 3300U
#define USER_POS_POT_EFFECTIVE_MAX (USER_POT_MAX - 2000U)
/*
 * Piecewise linear correction for non-linear slider response in position mode.
 * Example default:
 * - around raw 6300 should feel closer to 90 deg instead of only ~18 deg
 */
#define USER_POS_POT_BREAK_RAW 6300U
#define USER_POS_POT_BREAK_ANGLE_DEG10 900U

/* Shared AS5600 settings */
#define USER_AS5600_I2C_ADDR (0x36U << 1)

/* UART target stream from the remote ESP32S knob node */
#define USER_UART_TARGET_TIMEOUT_MS 100U

/* PWM target stream from the remote knob node */
#define USER_PWM_TARGET_MIN_PULSE_US 1000U
#define USER_PWM_TARGET_MAX_PULSE_US 2000U
#define USER_PWM_TARGET_TIMEOUT_MS 100U

/* Telemetry stream for the host-side angle monitor tool app */
#define USER_ANGLE_TELEMETRY_INTERVAL_MS 50U

/* User button debounce for runtime calibration actions */
#define USER_BUTTON_DEBOUNCE_MS 150U

/*
 * Knob-follow bootstrap:
 * - 1: assume the follower motor starts aligned with the external knob and
 *      seed the virtual follower angle from the AS5600 reading at boot.
 * - 0: require future manual seeding logic before the follower can move.
 */
#define USER_FOLLOW_BOOT_ASSUME_ALIGNED 1U

#if USER_MOTOR_PROFILE == USER_MOTOR_PROFILE_2216_920KV

#define USER_MOTOR_PROFILE_NAME "Holybro 2216 920KV"
#define USER_MOTOR_PROFILE_POLE_PAIRS 7

/* Throttle mode tuning for the original high-KV prop motor */
#define USER_THR_MIN_RPM 1800
#define USER_THR_MAX_RPM 8000
#define USER_THR_RAMP_MS 3000U

/* Position mode tuning if the 2216 is used with AS5600 */
#define USER_POS_MIN_RPM 1200
#define USER_POS_MAX_RPM 3500
#define USER_POS_ANGLE_DEADBAND_DEG 2
#define USER_POS_SPEED_KP_RPM_PER_DEG 25
#define USER_POS_RAMP_MS 150U
#define USER_POS_CURRENT_DIRECTION_SIGN 1
#define USER_POS_SPEED_DIRECTION_SIGN 1
#define USER_POS_SPEED_TO_CURRENT_DIRECTION_SIGN 1
#define USER_POS_SPEED_OUT_MIN_RPM 1200
#define USER_POS_SPEED_OUT_MAX_RPM 3500
#define USER_POS_SPEED_KD_RPM_PER_RPM 0
#define USER_POS_TARGET_RPM_SLEW_RPM_PER_TICK 300
#define USER_POS_SPEED_TO_CURRENT_KP_MA_PER_RPM 8
#define USER_POS_SPEED_KEEP_RUN_AT_ZERO 1U
#define USER_POS_CURRENT_KP_MA_PER_DEG 30
#define USER_POS_CURRENT_KD_MA_PER_RPM 2
#define USER_POS_MAX_CURRENT_MA 2000
#define USER_POS_MAX_CURRENT_A 2
#define USER_POS_HOLD_ENTER_DEG10 10
#define USER_POS_HOLD_EXIT_DEG10 20
#define USER_POS_SPEED_ZERO_WINDOW_RPM 30
#define USER_POS_CURRENT_ZERO_WINDOW_MA 30
#define USER_POS_CURRENT_SLEW_MA_PER_TICK 120
#define USER_POS_SPEED_LPF_SHIFT 2
#define USER_SENSORED_SPEED_ZERO_WINDOW_RPM 20

/* Sensored FOC skeleton settings */
#define USER_SENSORED_ALIGN_CURRENT_A 1
#define USER_SENSORED_ALIGN_DURATION_MS 250U
#define USER_SENSORED_ALIGN_LOCK_ELEC_DEG10 0
#define USER_SENSORED_ELEC_TRIM_DEG10 0
#define USER_SENSORED_DIRECTION_SIGN 1

#define USER_RUNTIME_TUNE_ENABLE 0
#define USER_RUNTIME_MAX_SPEED_RPM USER_THR_MAX_RPM
#define USER_RUNTIME_MAX_CURRENT_MA 3000
#define USER_RUNTIME_SPEED_PID_KP 3433
#define USER_RUNTIME_SPEED_PID_KI 2499
#define USER_RUNTIME_IQ_PID_KP 2081
#define USER_RUNTIME_IQ_PID_KI 3330
#define USER_RUNTIME_ID_PID_KP 2081
#define USER_RUNTIME_ID_PID_KI 3330

/* Fixed low-speed spin test */
#define USER_TEST_SPIN_RPM 1800
#define USER_TEST_SPIN_RAMP_MS 300U
#define USER_TEST_SPIN_DIRECTION_SIGN 1

/* Knob-follow tuning for 2804 + AS5600 driving the 2216 follower */
#define USER_FOLLOW_MIN_RPM 400
#define USER_FOLLOW_MAX_RPM 2200
#define USER_FOLLOW_ANGLE_DEADBAND_DEG 3
#define USER_FOLLOW_SPEED_KP_RPM_PER_DEG 18
#define USER_FOLLOW_RAMP_MS 150U
#define USER_FOLLOW_DIRECTION_SIGN 1

#define USER_STARTUP_PROFILE_NAME "MCSDK default 2216"
#define USER_STARTUP_OVERRIDE_ENABLE 0

#elif USER_MOTOR_PROFILE == USER_MOTOR_PROFILE_2804_100KV

#define USER_MOTOR_PROFILE_NAME "2804 100-110KV"
#define USER_MOTOR_PROFILE_POLE_PAIRS 7

/*
 * Conservative app-level limits for a low-KV 2804 gimbal-style outrunner.
 * The image you shared says:
 * - 100K~110KV
 * - 2S~4S LiPo
 * - 12N14P, so 7 pole pairs
 */
#define USER_THR_MIN_RPM 150
#define USER_THR_MAX_RPM 1400
#define USER_THR_RAMP_MS 4000U

#define USER_POS_MIN_RPM 120
#define USER_POS_MAX_RPM 600
#define USER_POS_ANGLE_DEADBAND_DEG 2
#define USER_POS_SPEED_KP_RPM_PER_DEG 8
#define USER_POS_RAMP_MS 250U
#define USER_POS_CURRENT_DIRECTION_SIGN 1
#define USER_POS_SPEED_DIRECTION_SIGN 1
#define USER_POS_SPEED_TO_CURRENT_DIRECTION_SIGN 1
#define USER_POS_SPEED_OUT_MIN_RPM 0
#define USER_POS_SPEED_OUT_MAX_RPM 220
#define USER_POS_SPEED_KD_RPM_PER_RPM 1
#define USER_POS_TARGET_RPM_SLEW_RPM_PER_TICK 40
#define USER_POS_SPEED_TO_CURRENT_KP_MA_PER_RPM 4
#define USER_POS_SPEED_KEEP_RUN_AT_ZERO 1U
#define USER_POS_CURRENT_KP_MA_PER_DEG 20
#define USER_POS_CURRENT_KD_MA_PER_RPM 2
#define USER_POS_MAX_CURRENT_MA 300
#define USER_POS_MAX_CURRENT_A 1
#define USER_POS_HOLD_ENTER_DEG10 20
#define USER_POS_HOLD_EXIT_DEG10 45
#define USER_POS_SPEED_ZERO_WINDOW_RPM 25
#define USER_POS_CURRENT_ZERO_WINDOW_MA 20
#define USER_POS_CURRENT_SLEW_MA_PER_TICK 20
#define USER_POS_SPEED_LPF_SHIFT 1
#define USER_SENSORED_SPEED_ZERO_WINDOW_RPM 8

#define USER_SENSORED_ALIGN_CURRENT_A 1
#define USER_SENSORED_ALIGN_DURATION_MS 350U
#define USER_SENSORED_ALIGN_LOCK_ELEC_DEG10 0
#define USER_SENSORED_ELEC_TRIM_DEG10 0
#define USER_SENSORED_DIRECTION_SIGN 1

#define USER_RUNTIME_TUNE_ENABLE 1
#define USER_RUNTIME_MAX_SPEED_RPM USER_THR_MAX_RPM
#define USER_RUNTIME_MAX_CURRENT_MA 300
#define USER_RUNTIME_SPEED_PID_KP 900
#define USER_RUNTIME_SPEED_PID_KI 40
#define USER_RUNTIME_IQ_PID_KP 320
#define USER_RUNTIME_IQ_PID_KI 64
#define USER_RUNTIME_ID_PID_KP 320
#define USER_RUNTIME_ID_PID_KI 64

#define USER_FOLLOW_MIN_RPM 80
#define USER_FOLLOW_MAX_RPM 500
#define USER_FOLLOW_ANGLE_DEADBAND_DEG 3
#define USER_FOLLOW_SPEED_KP_RPM_PER_DEG 6
#define USER_FOLLOW_RAMP_MS 250U
#define USER_FOLLOW_DIRECTION_SIGN 1

#if USER_STARTUP_PROFILE == USER_STARTUP_PROFILE_MCW_DEFAULT

#define USER_STARTUP_PROFILE_NAME "MCSDK default"
#define USER_STARTUP_OVERRIDE_ENABLE 0

#elif USER_STARTUP_PROFILE == USER_STARTUP_PROFILE_2804_GENTLE_SENSORLESS

#define USER_STARTUP_PROFILE_NAME "2804 gentle sensorless"
#define USER_STARTUP_OVERRIDE_ENABLE 1
#define USER_STARTUP_DEFAULT_TARGET_SPEED_RPM 500
#define USER_STARTUP_PHASE1_DURATION_MS 700
#define USER_STARTUP_PHASE1_FINAL_SPEED_RPM 0
#define USER_STARTUP_PHASE1_FINAL_CURRENT_A 2
#define USER_STARTUP_PHASE2_DURATION_MS 2200
#define USER_STARTUP_PHASE2_FINAL_SPEED_RPM 900
#define USER_STARTUP_PHASE2_FINAL_CURRENT_A 2
#define USER_STARTUP_ENABLE_SL_ALGO_FROM_PHASE 2
#define USER_STARTUP_OBS_MINIMUM_SPEED_RPM 700
#define USER_STARTUP_TRANSITION_DURATION_MS 50

#elif USER_STARTUP_PROFILE == USER_STARTUP_PROFILE_2804_LOW_SPEED_TEST

#define USER_STARTUP_PROFILE_NAME "2804 low-speed test"
#define USER_STARTUP_OVERRIDE_ENABLE 1
#define USER_STARTUP_DEFAULT_TARGET_SPEED_RPM 650
#define USER_STARTUP_PHASE1_DURATION_MS 900
#define USER_STARTUP_PHASE1_FINAL_SPEED_RPM 0
#define USER_STARTUP_PHASE1_FINAL_CURRENT_A 2
#define USER_STARTUP_PHASE2_DURATION_MS 2600
#define USER_STARTUP_PHASE2_FINAL_SPEED_RPM 650
#define USER_STARTUP_PHASE2_FINAL_CURRENT_A 2
#define USER_STARTUP_ENABLE_SL_ALGO_FROM_PHASE 2
#define USER_STARTUP_OBS_MINIMUM_SPEED_RPM 500
#define USER_STARTUP_TRANSITION_DURATION_MS 60

#else
#error "Unsupported USER_STARTUP_PROFILE for 2804"
#endif

/* Fixed low-speed spin test */
#define USER_TEST_SPIN_RPM 650
#define USER_TEST_SPIN_RAMP_MS 400U
#define USER_TEST_SPIN_DIRECTION_SIGN 1

#elif USER_MOTOR_PROFILE == USER_MOTOR_PROFILE_2804_220KV

#define USER_MOTOR_PROFILE_NAME "MKS YT2804 220KV"
#define USER_MOTOR_PROFILE_POLE_PAIRS 7

/*
 * Based on the spec photos you shared:
 * - DC12V (3S~4S)
 * - Phase resistance 5.2 ohm
 * - 220 KV
 * - Maximum speed 3840 RPM
 * - 7 pole pairs
 */
#define USER_THR_MIN_RPM 250
#define USER_THR_MAX_RPM 2800
#define USER_THR_RAMP_MS 3000U

#define USER_POS_MIN_RPM 180
#define USER_POS_MAX_RPM 900
#define USER_POS_ANGLE_DEADBAND_DEG 2
#define USER_POS_SPEED_KP_RPM_PER_DEG 4
#define USER_POS_RAMP_MS 350U
#define USER_POS_CURRENT_DIRECTION_SIGN -1
#define USER_POS_SPEED_DIRECTION_SIGN 1
#define USER_POS_SPEED_TO_CURRENT_DIRECTION_SIGN 1
#define USER_POS_SPEED_OUT_MIN_RPM 0
#define USER_POS_SPEED_OUT_MAX_RPM 120
#define USER_POS_SPEED_KD_RPM_PER_RPM 2
#define USER_POS_TARGET_RPM_SLEW_RPM_PER_TICK 12
#define USER_POS_SPEED_TO_CURRENT_KP_MA_PER_RPM 2
#define USER_POS_SPEED_KEEP_RUN_AT_ZERO 1U
#define USER_POS_CURRENT_KP_MA_PER_DEG 16
#define USER_POS_CURRENT_KD_MA_PER_RPM 4
#define USER_POS_MAX_CURRENT_MA 350
#define USER_POS_MAX_CURRENT_A 1
#define USER_POS_HOLD_ENTER_DEG10 15
#define USER_POS_HOLD_EXIT_DEG10 30
#define USER_POS_SPEED_ZERO_WINDOW_RPM 20
#define USER_POS_CURRENT_ZERO_WINDOW_MA 20
#define USER_POS_CURRENT_SLEW_MA_PER_TICK 8
#define USER_POS_SPEED_LPF_SHIFT 1
#define USER_SENSORED_SPEED_ZERO_WINDOW_RPM 5

#define USER_SENSORED_ALIGN_CURRENT_A 1
#define USER_SENSORED_ALIGN_DURATION_MS 300U
#define USER_SENSORED_ALIGN_LOCK_ELEC_DEG10 0
#define USER_SENSORED_ELEC_TRIM_DEG10 0
#define USER_SENSORED_DIRECTION_SIGN 1

#define USER_RUNTIME_TUNE_ENABLE 1
#define USER_RUNTIME_MAX_SPEED_RPM USER_THR_MAX_RPM
#define USER_RUNTIME_MAX_CURRENT_MA 350
#define USER_RUNTIME_SPEED_PID_KP 900
#define USER_RUNTIME_SPEED_PID_KI 40
#define USER_RUNTIME_IQ_PID_KP 384
#define USER_RUNTIME_IQ_PID_KI 64
#define USER_RUNTIME_ID_PID_KP 384
#define USER_RUNTIME_ID_PID_KI 64

#define USER_FOLLOW_MIN_RPM 120
#define USER_FOLLOW_MAX_RPM 700
#define USER_FOLLOW_ANGLE_DEADBAND_DEG 3
#define USER_FOLLOW_SPEED_KP_RPM_PER_DEG 8
#define USER_FOLLOW_RAMP_MS 220U
#define USER_FOLLOW_DIRECTION_SIGN 1

#if USER_STARTUP_PROFILE == USER_STARTUP_PROFILE_MCW_DEFAULT

#define USER_STARTUP_PROFILE_NAME "MCSDK default"
#define USER_STARTUP_OVERRIDE_ENABLE 0

#elif USER_STARTUP_PROFILE == USER_STARTUP_PROFILE_2804_GENTLE_SENSORLESS

#define USER_STARTUP_PROFILE_NAME "2804 gentle sensorless"
#define USER_STARTUP_OVERRIDE_ENABLE 1
#define USER_STARTUP_DEFAULT_TARGET_SPEED_RPM 900
#define USER_STARTUP_PHASE1_DURATION_MS 700
#define USER_STARTUP_PHASE1_FINAL_SPEED_RPM 0
#define USER_STARTUP_PHASE1_FINAL_CURRENT_A 2
#define USER_STARTUP_PHASE2_DURATION_MS 2000
#define USER_STARTUP_PHASE2_FINAL_SPEED_RPM 1200
#define USER_STARTUP_PHASE2_FINAL_CURRENT_A 2
#define USER_STARTUP_ENABLE_SL_ALGO_FROM_PHASE 2
#define USER_STARTUP_OBS_MINIMUM_SPEED_RPM 900
#define USER_STARTUP_TRANSITION_DURATION_MS 50

#elif USER_STARTUP_PROFILE == USER_STARTUP_PROFILE_2804_LOW_SPEED_TEST

#define USER_STARTUP_PROFILE_NAME "2804 low-speed test"
#define USER_STARTUP_OVERRIDE_ENABLE 1
#define USER_STARTUP_DEFAULT_TARGET_SPEED_RPM 800
#define USER_STARTUP_PHASE1_DURATION_MS 850
#define USER_STARTUP_PHASE1_FINAL_SPEED_RPM 0
#define USER_STARTUP_PHASE1_FINAL_CURRENT_A 2
#define USER_STARTUP_PHASE2_DURATION_MS 2300
#define USER_STARTUP_PHASE2_FINAL_SPEED_RPM 900
#define USER_STARTUP_PHASE2_FINAL_CURRENT_A 2
#define USER_STARTUP_ENABLE_SL_ALGO_FROM_PHASE 2
#define USER_STARTUP_OBS_MINIMUM_SPEED_RPM 700
#define USER_STARTUP_TRANSITION_DURATION_MS 60

#else
#error "Unsupported USER_STARTUP_PROFILE for 2804 220KV"
#endif

/* Fixed low-speed spin test */
#define USER_TEST_SPIN_RPM 900
#define USER_TEST_SPIN_RAMP_MS 350U
#define USER_TEST_SPIN_DIRECTION_SIGN 1

#else
#error "Unsupported USER_MOTOR_PROFILE"
#endif

#if USER_MOTOR_PROFILE_POLE_PAIRS != POLE_PAIR_NUM
#error "USER_MOTOR_PROFILE_POLE_PAIRS does not match POLE_PAIR_NUM from MCSDK-generated motor parameters."
#endif

#endif /* USER_CONFIG_H */
